version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
